version: '3'
services:
  prometheus:
    image: prom/prometheus
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.retention.size=3GB
    ports:
    - "10.10.40.101:9090:9090"
    volumes:
    - ./prometheus:/etc/prometheus:ro
    - prometheus_data:/prometheus
    depends_on:
    - exporter
    restart: always

  grafana:
    image: grafana/grafana
    env_file:
    - grafana.env
    ports:
    - "3000:3000"
    volumes:
    - grafana_etc:/etc/grafana
    - grafana_var_lib:/var/lib/grafana
    - ./provisioning:/etc/grafana/provisioning
    depends_on:
    - prometheus
    restart: always

  exporter:
    build: mining-exporter
    env_file:
      - mining_exporter.env
    restart: always

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/:ro
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    depends_on:
    - prometheus

  alertmanager-bot:
    image: metalmatze/alertmanager-bot
    restart: always
    env_file:
      - alertmanager_bot.env
    environment:
      ALERTMANAGER_URL: http://alertmanager:9093
      STORE: bolt
      BOLT_PATH: /data/bot.db
      TEMPLATE_PATHS: /templates/default.tmpl
    volumes:
    - alertmanager-bot_data:/data

  zerotier:
    image: zyclonite/zerotier
    restart: always
    network_mode: host
    privileged: true
    devices:
      - /dev/net/tun
    volumes:
      - zerotier_data:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  ethermine-exporter:
    image: hon95/prometheus-ethermine-exporter:1
    #command:
    #  - '--endpoint=:8080'
    #  - '--debug'
    #user: 1000:1000
    environment:
      - TZ=Asia/Novokuznetsk

  webhook-script:
    build: webhook-script
    restart: always
    env_file:
      - webhook-script.env
    volumes:
    - ./webhook-script/app:/app

volumes:
  grafana_var_lib:
  grafana_etc:
  alertmanager-bot_data:
  zerotier_data:
  prometheus_data:
