scrape_configs:
  - job_name: 'miner'
    static_configs:
      - targets: ['exporter:8080']

  - job_name: ethermine-ethermine-pool
    # Limit due to API rate restriction
    scrape_interval: 30m
    metrics_path: /pool
    params:
      pool: [ethermine]
    static_configs:
      - targets:
          - ethermine-exporter:8080

  - job_name: ethermine-ethermine-miner
    # Limit due to API rate restriction
    scrape_interval: 5m
    metrics_path: /miner
    params:
      pool: [ethermine]
    static_configs:
      - targets:
          - 7a8B6A25Ac4Ec001AeEcF9D130A0908494bA89Fa
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: ethermine-exporter:8080

global:
#  scrape_interval: 2m
#  evaluation_interval: 4m
#  scrape_timeout: 2m

alerting:
 alertmanagers:
   - static_configs:
     - targets:
       - alertmanager:9093

rule_files:
  - "alert.rules"
